# Generated by Django 5.1 on 2024-08-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=100)),
                ('vision', models.CharField(max_length=100)),
                ('objectives', models.CharField(max_length=100)),
            ],
        ),
    ]
